{{/* SPDX-License-Identifier: Apache-2.0 */ -}}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mcfreeze.controlPlane.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcfreeze.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "update", "delete", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["create", "get", "update", "delete", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete"]
  - apiGroups: ["mcfreeze.dev"]
    resources: ["datasets", "datasetversions", "datasetbindings"]
    verbs: ["create", "get", "update", "delete", "list", "watch", "patch"]
  - apiGroups: ["mcfreeze.dev"]
    resources: ["datasets/status", "datasetversions/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mcfreeze.controlPlane.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcfreeze.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
subjects:
  - kind: ServiceAccount
    name: {{ include "mcfreeze.controlPlane.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mcfreeze.controlPlane.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mcfreeze.controlPlane.name" . }}
  labels:
    {{- include "mcfreeze.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "get", "update", "delete", "list"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mcfreeze.controlPlane.name" . }}
  labels:
    {{- include "mcfreeze.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
subjects:
  - kind: ServiceAccount
    name: {{ include "mcfreeze.controlPlane.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mcfreeze.controlPlane.name" . }}
{{- end }}
