{{- if and .Values.rbac.create .Values.nodeAgent.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mcfreeze.nodeAgent.name" . }}
  labels:
    {{- include "mcfreeze.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-agent
rules:
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["create", "get", "delete", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mcfreeze.nodeAgent.name" . }}
  labels:
    {{- include "mcfreeze.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-agent
subjects:
  - kind: ServiceAccount
    name: {{ include "mcfreeze.nodeAgent.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mcfreeze.nodeAgent.name" . }}
{{- end }}
