{{/* SPDX-License-Identifier: Apache-2.0 */ -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcfreeze.controlPlane.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcfreeze.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
  {{- with .Values.serviceAccount.controlPlaneAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.nodeAgent.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcfreeze.nodeAgent.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcfreeze.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-agent
  {{- with .Values.serviceAccount.nodeAgentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcfreeze.builder.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcfreeze.labels" . | nindent 4 }}
    app.kubernetes.io/component: builder
  {{- with .Values.serviceAccount.builderAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
