{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frostmap.controlPlane.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frostmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
  {{- with .Values.serviceAccount.controlPlaneAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.nodeAgent.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frostmap.nodeAgent.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frostmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-agent
  {{- with .Values.serviceAccount.nodeAgentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frostmap.builder.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frostmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: builder
  {{- with .Values.serviceAccount.builderAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
