apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/rbac.yaml
  - ../base/service.yaml
  - ../base/control-plane.yaml
  - ../base/daemonset.yaml
patches:
  - target:
      kind: Deployment
      name: frostmap-control-plane
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: DaemonSet
      name: frostmap-node-agent
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
      - op: add
        path: /spec/template/spec/containers/1/imagePullPolicy
        value: Never
