# SPDX-License-Identifier: Apache-2.0
# KIND-specific overrides. Use with:
#   helm upgrade --install mcfreeze ./k8s/charts/mcfreeze \
#     -n mcfreeze-system --create-namespace \
#     -f ./k8s/charts/mcfreeze/values-kind.yaml --wait

image:
  tag: dev
  pullPolicy: Never

controlPlane:
  storageClass: csi-hostpath-sc
  diskSizeGB: 1
  leaderElection: false

nodeAgent:
  csiDriver: hostpath.csi.k8s.io
  mounter: fs
  csiHostPath: /var/lib/csi-hostpath-data
