{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frostmap.controlPlane.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frostmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
{{- if .Values.nodeAgent.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frostmap.nodeAgent.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frostmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-agent
{{- end }}
{{- end }}
